### PR TITLE
General updates to repository and project

### LINKED ISSUE #4: General Repository/Project Maintenance
@hadi77ir would you have any objections to me making a few small "tweaks" to this repository/project to bring it into line with some of the other projects in the Cake-Contrib Organisation?

There won't be any code related changes, just minor changes to repository files and NuGet metadata.  You can see similar changes that I have just made on this repository.

https://github.com/cake-contrib/Cake.MsDeploy

Thanks

### PR DESCRIPTION
**Pull request by gep13**
Fixes #4 

Let me know if you have any questions.

### CODE REVIEW

**Comment by gep13** [comment]
@hadi77ir thank you for taking the time to review and merge this, I appreciate it!

The updates to the NuGet metadata won't go live until a new release to NuGet.org is performed.  Do you have an upcoming release with any new features?  Or would it make sense to do a patch release to have these changes go live?

**Comment by hadi77ir** [comment]
@gep13 No, there aren't any upcoming releases currently. I think we should do a patch release.

**Comment by gep13** [comment]
@hadi77ir would you like me to take care of doing that, or would you like to do it?

**Comment by hadi77ir** [comment]
@gep13 Will appreciate it if you can take care of that. (I'm really a newbie :sweat_smile: )
Also I think we should move CI to cake-contrib, but I don't know if I should do anything about it or how to do that or even its possibility.

**Comment by gep13** [comment]
Perfect, I can take care of that this evening. I have already set up a new CI Build for this repo. If you log into AppVeyor with your GitHub account, you should have access to it. If you already had a CI Build setup, it would make sense to disable it now if that is ok.

I will leave notes about what process I have followed so that you know what I have done.

**Comment by gep13** [comment]
@hadi77ir these are the steps that I followed:

* Create [0.1.2](https://github.com/cake-contrib/Cake.Rest/milestone/1) milestone on GitHub
* Assigned [issue](https://github.com/cake-contrib/Cake.Rest/issues/4) to milestone
* Labelled issue as Improvement
* Fixed the broken AppVeyor build with this [commit](https://github.com/cake-contrib/Cake.Rest/commit/715925a51cf92beeb8bda9d309df7db4be3345c1)
* Made sure that issue linked above was closed and then ran the following locally `./build.sh --target=releasenotes`
* This created a draft release for 0.1.2 with all the issues (in this case only one) included within it
* I then edited this release and clicked the `Publish Release` button
* This kicked off another [AppVeyor build](https://ci.appveyor.com/project/cakecontrib/cake-rest/builds/26731526) this time with a tag
* Which causes things to actually get published.  Things that happened from this build:
  * Gitter message was sent [here](https://gitter.im/cake-contrib/Lobby?at=5d55bea62612bb718c73e19b)
  * Tweet was sent [here](https://twitter.com/cakecontrib/status/1162096848527663104)
  * GitHub Release was updated with assets [here](https://github.com/cake-contrib/Cake.Rest/releases/tag/0.1.2)
  * GitHub milestone was closed [here](https://github.com/cake-contrib/Cake.Rest/milestone/1)
  * NuGet Package was published to MyGet
  * NuGet Pacakge was published to [NuGet](https://www.nuget.org/packages/Cake.Rest/0.1.2)

Let me know if you have any questions about any of this.

**Pull request merged**
